GET http://localhost:3000/todos/?status=TO%20DO
###

GET http://localhost:3000/todos/?priority=HIGH
###
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
###
GET http://localhost:3000/todos/?search_q=Play
###
GET http://localhost:3000/todos/6/
###


POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 9,
  "todo": "Finalize event theme2",
  "priority": "LOW",
  "status": "TO DO"
}
###

PUT  http://localhost:3000/todos/:todoId/
Content-Type: application/json

{ "status": "DONE" }
###

DELETE  http://localhost:3000/todos/1/